site_name: PDM

repo_url: https://github.com/pdm-project/pdm
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
  custom_dir: docs/overrides

plugins:
  - search
  - markdown-exec
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - ç”¨æ³•:
      - ç®€ä»‹: index.md
      - usage/project.md
      - usage/dependency.md
      - usage/lockfile.md
      - usage/publish.md
      - usage/config.md
      - usage/scripts.md
      - usage/hooks.md
      - usage/advanced.md
      - usage/venv.md
      - usage/pep582.md
      - usage/template.md
  - å‚è€ƒ:
      - reference/pep621.md
      - reference/configuration.md
      - reference/build.md
      - reference/cli.md
      - reference/api.md
  - å¼€å‘:
      - dev/write.md
      - dev/fixtures.md
      - è´¡çŒ®æŒ‡å—: /en/latest/dev/contributing/
      - æ”¹åŠ¨æ—¥å¿—: /en/latest/dev/changelog/
      - dev/benchmark.md
  - èµåŠ©: https://github.com/sponsors/pdm-project

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: "#"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2019 <a href="https://frostming.com">Frost Ming</a>

extra:
  version:
    provider: mike
  analytics:
    provider: custom
    umami_site_id: d41bc972-79a4-4ce3-8c24-33026a8cdd9b
    umami_script: https://umami.fming.dev/script.js
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pdm-project/pdm
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pdm_project
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Phn8smztpv
  chatbot:
    url: https://2prxfnwkygf4vexczrbpcq.streamlit.app/?embed=true
  alternate:
    - name: 'ğŸ‡¬ğŸ‡§ English'
      link: /en/
      lang: en
    - name: 'ğŸ‡¨ğŸ‡³ ç®€ä½“ä¸­æ–‡'
      link: /zh-cn/
      lang: zh

extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js
